# Created 2021-06-07 Пн 06:21
#+AUTHOR: Renat Galimov

* Emacs CODE implementation                                         :project:
  Here will go the actual content we produce.
  [[id:93AE58FD-887D-4CFC-BF4E-2238BFA35A8F][Divergence and convergence]]

  Prerequisites:

  - [[https://github.com/org-roam/org-roam][GitHub - org-roam/org-roam: Rudimentary Roam replica with Org-mode]]

    This guide uses org-roam as the central tool to manage your notes.
    And this is the only prerequisite.

    Use a guide to set up either V1 or V2 version of org-roam.


** How to work with this guide?

   - Open this file in emacs.
   - Tangle a source block into your org directory.
   - Add the file to your load path.

** Prerequisites
*** Pandoc

    #+caption: Install pandoc on Ubuntu
    #+begin_src bash :exports code :eval never-export
      sudo apt install pandoc
    #+end_src

    #+caption: Install pandoc on Mac OS with homebrew
    #+begin_src bash :exports code :eval never-export
      brew install pandoc
    #+end_src

    Ensure that pandoc is in your path.

    #+caption: Pandoc version
    #+begin_src bash :exports both :eval never-export :results verbatim
      pandoc --version
    #+end_src

    #+RESULTS:
    : pandoc 2.14.0.2
    : Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
    : citeproc 0.4.0.1, ipynb 0.1.0.1
    : User data directory: /Users/renat.galimov/.local/share/pandoc
    : Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
    : This is free software; see the source for copying conditions. There is no
    : warranty, not even for merchantability or fitness for a particular purpose.
*** straight.el

    For this guide we will be using [[https://github.com/raxod502/straight.el][straight.el]] as your package manager.

    #+caption: Install straight.el
    #+begin_src emacs-lisp :exports code :eval never-export :results none
      (defvar bootstrap-version)
      (let ((bootstrap-file
             (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
            (bootstrap-version 5))
        (unless (file-exists-p bootstrap-file)
          (with-current-buffer
              (url-retrieve-synchronously
               "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
               'silent 'inhibit-cookies)
            (goto-char (point-max))
            (eval-print-last-sexp)))
        (load bootstrap-file nil 'nomessage))
    #+end_src

** Capture

   - Emacs is a text editor.
     You need to represent everything that you capture into a text.

   - Capture targets:
     - Web-pages
     - E-books
     - Documents
     - Videos
     - Audios
     - Images


   To capture we use pandoc and [[https://github.com/tecosaur/org-pandoc-import][org-pandoc-import]]

   #+name: install-org-pandoc-import
   #+begin_src emacs-lisp
     (use-package org-pandoc-import
       :straight (:host github
                        :repo "tecosaur/org-pandoc-import"
                        :files ("*.el" "filters" "preprocessors")))
   #+end_src

   I can convert almost any text format to org-mode representation.

   - Capture templates
     - Project


** Organize

   - Org roam links
   - Org-mode tags

** Distill

** Express

   - Exporting
   - Publishing


* Emacs config

  #+begin_src emacs-lisp :noweb yes :tangle ~/emacs/rc/CODE.el
    <<install-pandoc-import>>

  #+end_src

  #+RESULTS:


* Awesome Emacs Code
