# Created 2021-06-07 Пн 06:21
#+AUTHOR: Renat Galimov

* Emacs CODE implementation                                         :project:
  Here will go the actual content we produce.
  [[id:93AE58FD-887D-4CFC-BF4E-2238BFA35A8F][Divergence and convergence]]

  Prerequisites:

  - [[https://github.com/org-roam/org-roam][GitHub - org-roam/org-roam: Rudimentary Roam replica with Org-mode]]

    This guide uses org-roam as the central tool to manage your notes.
    And this is the only prerequisite.

    Use a guide to set up either V1 or V2 version of org-roam.


** How to work with this guide?

   - Open this file in emacs.
   - Tangle a source block into your org directory.
   - Add the file to your load path.

** Capture

   - Emacs is a text editor.
     You need to represent everything that you capture into a text.


   - Capture targets:
     - Web-pages
     - E-books
     - Documents
     - Videos
     - Audios
     - Images


   - Capture templates
     - Project
       This template will create a project entry and will ask you to set a deadline.
       #+caption: Capture project template
       #+name: roam-capture-project
       #+begin_src emacs-lisp
         (add-to-list
          'org-roam-capture-templates
          ("p" "Project" plain "%?"
           :if-new (file+head "roam/%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+roam_tags project\n\n* ${title}\n  :DEADLINE: %^{Project deadline}t\n\n")
           :unnarrowed t))
       #+end_src

** Organize

   - Org roam links
   - Org-mode tags

** Distill

** Express

   - Exporting
   - Publishing


* Awesome Emacs Code
