# Created 2021-06-07 Пн 06:21
#+AUTHOR: Renat Galimov

* Emacs CODE implementation                                         :project:

** Prerequisites

   - [[https://github.com/org-roam/org-roam][GitHub - org-roam/org-roam: Rudimentary Roam replica with Org-mode]]

     This guide uses org-roam as the central tool to manage your notes.
     And this is the only prerequisite.

     Use a guide to set up either the V1 or V2 version of org-roam.


** How to work with this guide?
   - Open this file in Emacs.
   - [[https://orgmode.org/manual/Extracting-Source-Code.html][Extract]] the [[*Emacs config][config]] source block into your org directory.
   - Add the resulting file to your load path.

** Prerequisites
*** Pandoc

    #+caption: Install Pandoc on Ubuntu
    #+begin_src bash :exports code :eval never-export
      sudo apt install pandoc
    #+end_src

    #+caption: Install Pandoc on Mac OS with homebrew
    #+begin_src bash :exports code :eval never-export
      brew install pandoc
    #+end_src

    Ensure that Pandoc is in your path.

    #+caption: Pandoc version
    #+begin_src bash :exports both :eval never-export :results verbatim
      pandoc --version
    #+end_src

    #+RESULTS:
    : pandoc 2.14.0.2
    : Compiled with pandoc-types 1.22, texmath 0.12.3, skylighting 0.10.5.1,
    : citeproc 0.4.0.1, ipynb 0.1.0.1
    : User data directory: /Users/renat.galimov/.local/share/pandoc
    : Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
    : This is free software; see the source for copying conditions. There is no
    : warranty, not even for merchantability or fitness for a particular purpose.
*** straight.el

    For this guide, we will be using [[https://github.com/raxod502/straight.el][straight.el]] as your package manager.

    #+caption: Install straight.el
    #+begin_src emacs-lisp :exports code :eval never-export :results none
      (defvar bootstrap-version)
      (let ((bootstrap-file
             (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
            (bootstrap-version 5))
        (unless (file-exists-p bootstrap-file)
          (with-current-buffer
              (url-retrieve-synchronously
               "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
               'silent 'inhibit-cookies)
            (goto-char (point-max))
            (eval-print-last-sexp)))
        (load bootstrap-file nil 'nomessage))
    #+end_src

** Capture

   - Emacs is a text editor.
     You have to represent everything that you capture as a text.

   - Capture targets:
     - Web-pages
     - E-books
     - Documents
     - Videos
     - Audios
     - Images

   To capture we use Pandoc and [[https://github.com/tecosaur/org-pandoc-import][org-pandoc-import]]

   #+name: install-org-pandoc-import
   #+begin_src emacs-lisp
     (use-package org-pandoc-import
       :straight (:host github
                        :repo "tecosaur/org-pandoc-import"
                        :files ("*.el" "filters" "preprocessors")))
   #+end_src

   Pandoc can convert almost any text format to org-mode
   representation. One of the current drawbacks - it cannot import online web pages.

   Another package - [[https://github.com/alphapapa/org-web-tools][org-web-tools]] offers
   =org-web-tools-read-url-as-org= function tha will download the URL
   to an org buffer.

   #+name: install-org-web-tools
   #+begin_src emacs-lisp
     (use-package org-web-tools :ensure t)
   #+end_src

   Often, downloaded files need manual cleanup.

   The third approach is to use a web-clipper and Pandoc.

   - Open the web article in your browser and activate a web-clipper.
     I use Firefoxes built-in one.
   - Save entire HTML into a file.
   - Convert the HTML with Pandoc
     #+caption: Convert HTML to Org with Pandoc
     #+begin_src bash
       pandoc -f html -t org <source-file>.html -o <target-file>.org
     #+end_src

     The resulting file might require some cleanup, but the quality of
     the output is the best among other methods.

   - Capture templates
     <<Please, contribute your capture templates>>

** Organize

   - Org roam links
   - Org-mode tags

** Distill

** Express

   - Exporting
   - Publishing


* Emacs config

  #+caption: Config source block
  #+begin_src emacs-lisp :noweb yes :tangle ~/emacs/rc/CODE.el
    <<install-pandoc-import>>
    <<install-org-web-tools>>
  #+end_src

  #+RESULTS:


* Awesome Emacs Code
