name: "Emacs 28 build check"
on:
  push:
    branches:
      - main
      - workflow-test

jobs:
  test-28.1:
    runs-on: ubuntu-20.04
    container: silex/emacs:28.1-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          apt update &&
          apt install -q -yy \
              git \
              autoconf \
              automake \
              libpng-dev \
              zlib1g-dev \
              libpoppler-glib-dev \
              libpoppler-private-dev

      - name: Emacs test
        run: emacs --batch -l ./bin/run-test.el
