name: "Emacs 28 build check"
on:
  push:
    branches:
      - main
      - workflow-test

jobs:
  test:
    runs-on: ubuntu-20.04
    container: alpine:3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update apk
        run: >
          apk update

      - name: Install dependencies
        run: >
          apk add ca-certificates emacs imagemagick git autoconf automake libpng-dev zlib-dev poppler-dev

      - name: Emacs test
        run: sh bin/test-emacs-28.1.sh
